import { SessionProvider } from 'next-auth/react';
import type { Metadata } from 'next';
import Link from 'next/link';
import localFont from 'next/font/local';
import { auth } from '@/lib/auth';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang='ko'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className='fixed top-0 flex h-12 w-full items-center justify-between bg-green-500 p-2'>
          <a href='/' className='text-2xl font-extrabold text-white'>
            나만의 레시피
          </a>
          <div className='m-1 flex gap-2'>
            {session?.user ? (
              <Link
                href='/addRecipe'
                className='m-1 rounded-lg border border-blue-500 bg-blue-500 p-1 font-semibold text-white'
              >
                레시피 추가
              </Link>
            ) : (
              <></>
            )}
            {session?.user ? (
              <Link
                href='/api/auth/signout'
                className='m-1 rounded-lg border border-red-500 bg-red-500 p-1 font-semibold text-white'
              >
                로그아웃
              </Link>
            ) : (
              <Link
                href='/api/auth/signin'
                className='m-1 rounded-lg border border-red-500 bg-red-500 p-1 font-semibold text-white'
              >
                로그인
              </Link>
            )}
          </div>
        </nav>
        <main className='mb-2 mt-12'>
          <SessionProvider session={session}>{children}</SessionProvider>
        </main>
      </body>
    </html>
  );
}
